spring:
  application:
    name: TreasureHunter
  datasource:
    url: jdbc:postgresql://localhost:5432/treasure_hunter
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jooq:
    sql-dialect: POSTGRES

jwt:
  secret: privateKey_it_is_short_so_I_add_some_characters
  expiration: 1d